In [2]:
import pandas as pd

In [3]:
salario = pd.read_csv('salarios.csv')
salario

                 Nome  Idade     Salário
0       Colby Bezerra     39   $3,655.82
1     Raphael Caetano     28   $3,434.08
2      Vivien Moreira     44   $5,758.39
3     Dominic Pacheco     18   $6,746.30
4      Colorado Felix     53   $5,120.70
5         Lucy Borges     38   $8,357.69
6          Levi Alves     41   $9,724.53
7       Joseph Nonato     32   $2,410.71
8       Kenyon Cabral     33   $9,532.24
9        Quinn Vieira     43   $9,148.76
10  Ferris de Andrade     54  $10,287.78
11    Giselle Ribeiro     48   $7,651.70
12   Chancellor Viana     38   $7,849.33
13         Troy Faria     55   $3,496.81
14    Delilah Bezerra     42  $10,270.19

In [10]:
salario['Salario_Float'] = salario['Salario'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\vsmvi\AppData\Local\Temp\ipykernel_36568\3571913605.py:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  salario['Salario_Float'] = salario['Salario'].replace('[\$,]', '', regex=True).astype(float)
C:\Users\vsmvi\AppData\Local\Temp\ipykernel_36568\3571913605.py:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  salario['Salario_Float'] = salario['Salario'].replace('[\$,]', '', regex=True).astype(float)

KeyError: 'Salario'

In [4]:
salario.rename(columns = {'Nome': 'Colaborador(a)'}).tail(7)

       Colaborador(a)  Idade     Salário
8       Kenyon Cabral     33   $9,532.24
9        Quinn Vieira     43   $9,148.76
10  Ferris de Andrade     54  $10,287.78
11    Giselle Ribeiro     48   $7,651.70
12   Chancellor Viana     38   $7,849.33
13         Troy Faria     55   $3,496.81
14    Delilah Bezerra     42  $10,270.19

In [5]:
mais_novo = salario.loc[salario['Idade']==salario['Idade'].min()]
mais_novo

              Nome  Idade    Salário
3  Dominic Pacheco     18  $6,746.30

In [ ]:
maior_salario = salario.loc[salario['Salario']==salario['Salario'].max()]
maior_salario